"""empty message

Revision ID: 2fcccec4ba5e
Revises: 5b2a187cb85e
Create Date: 2020-08-28 14:21:01.944155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcccec4ba5e'
down_revision = '5b2a187cb85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_creation_date', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('post_creation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_creation_date')
    op.drop_column('comment', 'comment_creation_date')
    # ### end Alembic commands ###
